### ISSUE TITLE
Out of bounds error causes a hang

### ISSUE THREAD

**Issue by mortvest** [pepijndevos/futhark-pycffi#25]
This [program](https://gist.github.com/mortvest/a318c4031f579d08dd1f306452a3e635) has an out of bounds error. When compiled with the opencl backend, it causes a hang instead of raising an ValueError (works as intended with c backend)

**Comment by athas** [comment]
Well, the type of the input is wrong here (`np.arange` produces 64-bit ints), but I don't know if that is the cause.

**Comment by mortvest** [comment]
[Fixed](https://gist.github.com/mortvest/a318c4031f579d08dd1f306452a3e635) it. Sadly, the problem remains.

**Comment by athas** [comment]
The problem is due to Futhark's asynchronous error detection ([documented here](https://futhark.readthedocs.io/en/latest/c-api.html)).  The entry point will return a succesfull error code, but it will actually fail in its outstanding operations, as can be detected by calling the sync function.  Two options are open to us:

1. Always synchronise after calling an entry point.  This will have some overhead for small entry points.
2. Remember that the objects returned may not be valid yet, and we need to sync (and do error detection) before we touch them.

**Comment by athas** [comment]
I thought option (2) would be very difficult to implement, but apparently not - at least not with the (slightly naive) solution of just syncing initially in `from_futhark`.
